### ISSUE TITLE
None of the transform animations are working when using appfairy

### ISSUE THREAD

**Issue by kaustubhamrit** [DAB0mB/Appfairy#9]
The js button interactions are working but none of the other view related animations are working.

**Comment by jayb967** [comment]
It's because appfairy doesn't refactor the Interactions portion of your main js file. There's three sections in that huge file, the last two sections need to be manually changed to match the new "af-class"'s along with the page id. Take a look at my open issue here: [https://github.com/DAB0mB/Appfairy/issues/7](url)

**Comment by DAB0mB** [comment]
Fixed in version 0.8.0
